/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thesisselectionsystem;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.*;
/**
 *
 * @author DOLPHIN
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        new Thread()
        {
        public void run()
        {
            while(true)
            {
                Calendar cal = new GregorianCalendar();
                int hour = cal.get(Calendar.HOUR);
                int min  = cal.get(Calendar.MINUTE);
                int sec = cal.get(Calendar.SECOND);
                int AM_PM = cal.get(Calendar.AM_PM);
                int day = cal.get(Calendar.DAY_OF_MONTH);
                int month=  cal.get(Calendar.MONTH);
                int year = cal.get((Calendar.YEAR));
                String am;
                if(0 == AM_PM)am="AM";
                else am = "PM";
                if(hour==0)hour =12;
                month++;
                String shour = String.format("%02d",hour);
                String smin = String.format("%02d",min);
                String ssec = String.format("%02d",sec);
                String timeString = hour + ":"+ smin + ":" + ssec + " " + am;
                String calString = day + "-"+ month +"-"+year;    
                DeskClock.setText(timeString);
                DeskCal.setText(calString);   
            }         
        }      
        }.start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        officePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        superviserPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        studentPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        helpPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        distribPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        thesisPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DeskCal = new javax.swing.JLabel();
        DeskClock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TSDS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setFocusTraversalPolicyProvider(true);
        setName("Home"); // NOI18N
        setUndecorated(true);

        panel1.setBackground(new java.awt.Color(197, 227, 227));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/system-analysis-icon_1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(197, 227, 227));
        jLabel3.setText("Thesis Selection and Distribution System");

        jLabel15.setBackground(new java.awt.Color(197, 227, 227));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 255, 255));
        jLabel15.setText("X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addContainerGap(119, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        officePanel.setBackground(new java.awt.Color(197, 227, 227));
        officePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                officePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                officePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                officePanelMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Slab", 0, 11)); // NOI18N
        jLabel2.setText("Office");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Users-Administrator-icon.png"))); // NOI18N

        javax.swing.GroupLayout officePanelLayout = new javax.swing.GroupLayout(officePanel);
        officePanel.setLayout(officePanelLayout);
        officePanelLayout.setHorizontalGroup(
            officePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(officePanelLayout.createSequentialGroup()
                .addGroup(officePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(officePanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2))
                    .addGroup(officePanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        officePanelLayout.setVerticalGroup(
            officePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, officePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        superviserPanel.setBackground(new java.awt.Color(197, 227, 227));
        superviserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                superviserPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                superviserPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                superviserPanelMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Slab", 0, 11)); // NOI18N
        jLabel4.setText("Supervisor");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Science-Classroom-icon.png"))); // NOI18N

        javax.swing.GroupLayout superviserPanelLayout = new javax.swing.GroupLayout(superviserPanel);
        superviserPanel.setLayout(superviserPanelLayout);
        superviserPanelLayout.setHorizontalGroup(
            superviserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superviserPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(superviserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        superviserPanelLayout.setVerticalGroup(
            superviserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, superviserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        studentPanel.setBackground(new java.awt.Color(197, 227, 227));
        studentPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentPanelMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Slab", 0, 11)); // NOI18N
        jLabel5.setText("Student");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Student-Male-icon.png"))); // NOI18N

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5))
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        helpPanel.setBackground(new java.awt.Color(197, 227, 227));
        helpPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpPanelMousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Network-Question-Shield-icon.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Roboto Slab", 0, 11)); // NOI18N
        jLabel6.setText("Help");

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addGroup(helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(helpPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel11))
                    .addGroup(helpPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel6)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        distribPanel.setBackground(new java.awt.Color(197, 227, 227));
        distribPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                distribPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                distribPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                distribPanelMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Slab", 0, 11)); // NOI18N
        jLabel7.setText("Distribution");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/File-HorizontalText-icon.png"))); // NOI18N

        javax.swing.GroupLayout distribPanelLayout = new javax.swing.GroupLayout(distribPanel);
        distribPanel.setLayout(distribPanelLayout);
        distribPanelLayout.setHorizontalGroup(
            distribPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distribPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(distribPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel7))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        distribPanelLayout.setVerticalGroup(
            distribPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distribPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        thesisPanel.setBackground(new java.awt.Color(197, 227, 227));
        thesisPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                thesisPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thesisPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                thesisPanelMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto Slab", 0, 11)); // NOI18N
        jLabel13.setText("Research Areas");

        jLabel12.setBackground(new java.awt.Color(197, 227, 227));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Books-2-icon.png"))); // NOI18N

        javax.swing.GroupLayout thesisPanelLayout = new javax.swing.GroupLayout(thesisPanel);
        thesisPanel.setLayout(thesisPanelLayout);
        thesisPanelLayout.setHorizontalGroup(
            thesisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thesisPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(thesisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        thesisPanelLayout.setVerticalGroup(
            thesisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thesisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DeskCal.setBackground(new java.awt.Color(255, 255, 255));
        DeskCal.setFont(new java.awt.Font("Gadugi", 1, 28)); // NOI18N
        DeskCal.setForeground(new java.awt.Color(0, 0, 51));
        DeskCal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        DeskClock.setBackground(new java.awt.Color(255, 255, 255));
        DeskClock.setFont(new java.awt.Font("Gadugi", 1, 28)); // NOI18N
        DeskClock.setForeground(new java.awt.Color(0, 0, 51));
        DeskClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(thesisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(officePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(superviserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(distribPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(DeskClock, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(helpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeskCal, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeskClock, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeskCal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(superviserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(officePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(thesisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(helpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(distribPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    
    
    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel15MousePressed

    private void officePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_officePanelMouseEntered
        // TODO add your handling code here:
        setColor(officePanel);
    }//GEN-LAST:event_officePanelMouseEntered

    private void officePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_officePanelMouseExited
        // TODO add your handling code here:
        resetColor(officePanel);
    }//GEN-LAST:event_officePanelMouseExited

    private void superviserPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_superviserPanelMouseEntered
        // TODO add your handling code here:
        setColor(superviserPanel);
    }//GEN-LAST:event_superviserPanelMouseEntered

    private void superviserPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_superviserPanelMouseExited
        // TODO add your handling code here:
        resetColor(superviserPanel);
    }//GEN-LAST:event_superviserPanelMouseExited

    private void studentPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentPanelMouseEntered
          // TODO add your handling code here:
        setColor(studentPanel);
        
    }//GEN-LAST:event_studentPanelMouseEntered

    private void studentPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentPanelMouseExited
        // TODO add your handling code here:
        resetColor(studentPanel);
    }//GEN-LAST:event_studentPanelMouseExited

    private void thesisPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thesisPanelMouseEntered
        // TODO add your handling code here:
        setColor(thesisPanel);
    }//GEN-LAST:event_thesisPanelMouseEntered
    
    private void distribPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distribPanelMouseEntered
        // TODO add your handling code here:
        setColor(distribPanel);
    }//GEN-LAST:event_distribPanelMouseEntered
                                         

    private void distribPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distribPanelMouseExited
        // TODO add your handling code here:
        resetColor(distribPanel);
    }//GEN-LAST:event_distribPanelMouseExited

    private void helpPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpPanelMouseEntered
        // TODO add your handling code here:
        setColor(helpPanel);
    }//GEN-LAST:event_helpPanelMouseEntered

    private void helpPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpPanelMouseExited
        // TODO add your handling code here:
        resetColor(helpPanel);
    }//GEN-LAST:event_helpPanelMouseExited

    private void thesisPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thesisPanelMouseExited
        // TODO add your handling code here:
        resetColor(thesisPanel);
    }//GEN-LAST:event_thesisPanelMouseExited

    private void officePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_officePanelMousePressed
        // TODO add your handling code here:
        new OfficeLoginFrame().show();
    }//GEN-LAST:event_officePanelMousePressed

    private void superviserPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_superviserPanelMousePressed
        // TODO add your handling code here:
        new SupervisorLoginFrame().show();
        
    }//GEN-LAST:event_superviserPanelMousePressed

    private void studentPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentPanelMousePressed
        // TODO add your handling code here:
        new StudentLoginFrame().show();
    }//GEN-LAST:event_studentPanelMousePressed

    private void helpPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpPanelMousePressed
        // TODO add your handling code here:
        new HelpFrame().show();
    }//GEN-LAST:event_helpPanelMousePressed

    private void distribPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distribPanelMousePressed
        // TODO add your handling code here:
        
        
        
        new DistFrame().show();
        
    }//GEN-LAST:event_distribPanelMousePressed

    private void thesisPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thesisPanelMousePressed
        // TODO add your handling code here:
        new ResearchFrame().show();
        
    }//GEN-LAST:event_thesisPanelMousePressed
    
    
    public void setColor(JPanel panel)
    {
        panel.setBackground(new java.awt.Color(159,202,224));
    }
    
    public void resetColor(JPanel panel)
    {
        panel.setBackground(new java.awt.Color(197,227,227));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeskCal;
    private javax.swing.JLabel DeskClock;
    private javax.swing.JPanel distribPanel;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel officePanel;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JPanel superviserPanel;
    private javax.swing.JPanel thesisPanel;
    // End of variables declaration//GEN-END:variables
}
